version: "3.8"

services:

  mariadb:
    image: mariadb:latest
    container_name: uptime_monitor_mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/mariadb-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monitor-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: uptime_monitor_clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./docker/clickhouse/clickhouse-init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - monitor-network

  node-monitor-api:
    build:
      context: .
      dockerfile: docker/APIDockerfile
    image: node-monitor-api:latest
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - mariadb
      - clickhouse
    networks:
      - monitor-network

  node-monitor:
    build:
      context: .
      dockerfile: docker/MonitorDockerfile
    image: node-monitor:latest
    ports:
      - "9091:9091"
    restart: always
    depends_on:
      - mariadb
      - clickhouse
    networks:
      - monitor-network

volumes:
  clickhouse_data:
  mariadb_data:

networks:
  monitor-network:
    driver: bridge